# Generated by Django 4.1.7 on 2023-06-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategorydb',
            name='Description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
