# Generated by Django 4.1.7 on 2023-06-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0003_subeventdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Subcategory_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Event_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Event_Description', models.CharField(blank=True, max_length=500, null=True)),
                ('Event_Image', models.ImageField(upload_to='Event')),
            ],
        ),
    ]
