# Generated by Django 4.1.7 on 2023-06-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0004_eventdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Subcategory_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Movie_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Movie_Description', models.CharField(blank=True, max_length=500, null=True)),
                ('Movie_Cast', models.CharField(blank=True, max_length=100, null=True)),
                ('Movie_time', models.CharField(blank=True, max_length=50, null=True)),
                ('Movie_Image', models.ImageField(upload_to='Movie')),
            ],
        ),
        migrations.DeleteModel(
            name='EventDB',
        ),
    ]
