# Generated by Django 4.1.7 on 2023-06-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0005_moviedb_delete_eventdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedb',
            name='Movie_time',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
