# Generated by Django 4.1.7 on 2023-06-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0007_alter_moviedb_movie_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedb',
            name='Movie_time',
        ),
        migrations.AddField(
            model_name='moviedb',
            name='Movie_Time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
