# Generated by Django 4.1.7 on 2023-06-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0008_remove_moviedb_movie_time_moviedb_movie_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Subcategory_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Match_Info', models.CharField(blank=True, max_length=100, null=True)),
                ('Match_Venue', models.CharField(blank=True, max_length=50, null=True)),
                ('Match_Date', models.CharField(blank=True, max_length=50, null=True)),
                ('Match_Time', models.CharField(blank=True, max_length=50, null=True)),
                ('Match_Image', models.ImageField(upload_to='Sports')),
            ],
        ),
    ]
