# Generated by Django 4.1.7 on 2023-06-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0009_sportsdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedb',
            name='Movie_Screen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='moviedb',
            name='Show_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
