# Generated by Django 4.1.7 on 2023-06-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0010_moviedb_movie_screen_moviedb_show_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField()),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='moviedb',
            old_name='Show_time',
            new_name='Show_Time',
        ),
    ]
