# Generated by Django 4.1.7 on 2023-06-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0013_remove_bookingdb_date_remove_bookingdb_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Seat', models.CharField(blank=True, max_length=50, null=True)),
                ('Movie', models.CharField(blank=True, max_length=100, null=True)),
                ('Screen', models.CharField(blank=True, max_length=100, null=True)),
                ('Time', models.IntegerField(blank=True, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='Screen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='Time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
