# Generated by Django 4.1.7 on 2023-06-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0014_detailsdb_bookingdb_screen_bookingdb_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdb',
            name='Time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detailsdb',
            name='Time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
