# Generated by Django 4.1.7 on 2023-07-02 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0016_bookingconfirm_remove_detailsdb_movie_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingConfirm',
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
