# Generated by Django 4.1.7 on 2023-07-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0017_delete_bookingconfirm_bookingdb_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdb',
            name='Name',
        ),
        migrations.AlterField(
            model_name='bookingdb',
            name='Seat',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
