# Generated by Django 4.1.7 on 2023-07-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0019_bookingdb_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdb',
            name='Seat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
