# Generated by Django 4.1.7 on 2023-07-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0021_admindb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
