# Generated by Django 4.1.7 on 2023-07-04 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0024_remove_bookingdb_date_detailsdb_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsdb',
            name='Date',
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
